---
- name: Install Falcon-sensor and Nessus agent
  hosts: all
  become: true
  
  vars:
    GOOGLE_CREDENTIALS: "{{ lookup('env', 'GOOGLE_CREDENTIALS') }}"

  tasks:
    - name: Install Python dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - gcc
        - openssl-devel
        - bzip2-devel
        - libffi-devel

    - name: Install google-cloud-storage
      pip:
        name: google-cloud-storage
        executable: pip3
        
    - name: Print pwd 
      shell: pwd

    - name: Display secret value
      debug:
        var: lookup('env', 'GOOGLE_CREDENTIALS')

    #- name: Print cred secrets
    # shell: echo "${{ secrets.GOOGLE_CREDENTIALS }}"
    #  register: g_cred
    
    #- name: Print uptime of managed node
    #  debug:
    #     var: "{{ g_cred.stdout }}"

    - name: Download an object
      google.cloud.gcp_storage_object:
        action: download
        bucket: testdownload12345
        src: jre-8u371-linux-x64.rpm
        dest: "/tmp/jre-8u371-linux-x64.rpm"
        project: test_project
        auth_kind: serviceaccount
        service_account_file: "{{ GOOGLE_CREDENTIALS }}"
        ##service_account_file: "{{ lookup('env', 'GOOGLE_CREDENTIALS') }}"
      register: download_result
      
    - name: Check the download status
      debug:
        msg: "Download status: {{ download_result }}"
 

    - name: Copy file to remote server
      copy:
        src: ./Ansible/install_java.yml
        dest: /tmp/


    - name: Copy file to remote server
      copy:
        src: ./../gcp.ppk
        dest: /tmp/
