---
- name: Install Falcon-sensor and Nessus agent
  hosts: ALL
  become: true
  

  tasks:


    - name: Download some content
      gc_storage:
        bucket: testdownload12345
        object: jre-8u371-linux-x64.rpm 
        dest: /tmp/jre-8u371-linux-x64.rpm 
        mode: get
 

    - name: Install JAVA
      yum:
        name: "/tmp/jre-8u371-linux-x64.rpm"
        state: present
