---
- name: Install Falcon-sensor and Nessus agent
  hosts: all
  become: true
  

  tasks:

    - name: Download an object
      google.cloud.gcp_storage_object:
        action: download
        bucket: testdownload12345
        src: jre-8u371-linux-x64.rpm
        dest: "/tmp/jre-8u371-linux-x64.rpm"
        project: test_project
        auth_kind: serviceaccount
        service_account_file: "./ninth-beacon-388117-d7f8eeedc1e1.json"
      register: download_result
      
    - name: Check the download status
      debug:
        msg: "Download status: {{ download_result }}"
 

    - name: Copy file to remote server
      copy:
        src: ./Ansible/install_java.yml
        dest: /tmp/


    - name: Copy file to remote server
      copy:
        src: ./../gcp.ppk
        dest: /tmp/
