---
- name: Install Falcon-sensor and Nessus agent
  hosts: all
  become: true
  

  tasks:


    - name: Download some content
      gc_storage:
        bucket: testdownload12345
        object: jre-8u371-linux-x64.rpm 
        dest: /tmp/jre-8u371-linux-x64.rpm 
        mode: get
 

    - name: Copy file to remote server
      copy:
        src: ./Ansible/install_java.yml
        dest: /tmp/


    - name: Copy file to remote server
      copy:
        src: ./../gcp.ppk
        dest: /tmp/
