test12345name: Terraform Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ninth-beacon-388117
        service_account_key: ${{ secrets.GOOGLE_CRED }}
        export_default_credentials: true


    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan -var "my_secret_pub=${{ secrets.SSH_PUBLIC_KEY }}" -var "my_secret_pvt=${{ secrets.SSH_PVT_KEY }}"

    - name: Terraform Apply
      run: terraform apply tfplan
      env:
        TF_VAR_project_id: ninth-beacon-388117
        
    - name: Install Ansible
      run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible
          python -m pip install --upgrade pip
          python -m pip install google-cloud-storage
          sudo apt-get update

    - name: Execute Ansible playbook
      run: |
          #echo "${{ secrets.GOOGLE_CREDENTIALS }}" > google_credentials.json
          echo "${{ secrets.SSH_PVT_KEY }}" > key.pem
          chmod 600 key.pem
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.ini ./Ansible/install_java.yml -u gcp --private-key key.pem -vvv
      env:
          SSH_PVT_KEY: ${{ secrets.SSH_PVT_KEY }}
          #GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
